"""Add unique constraints to username and email

Revision ID: 4bed9cff9865
Revises: 37b55d13a802
Create Date: 2024-05-10 17:35:01.250395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bed9cff9865'
down_revision = '37b55d13a802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
